"""Единый источник parity-критичных дефолтов Takt."""

TAKT_NO_CAR_SHARE = 0.35
TAKT_NO_CAR_FACTOR = 0.78
TAKT_VOT_S_PER_EUR = 360.0

TAKT_WALK_SPEED_MPS = 1.33
TAKT_WALK_CIRCUITY = 1.25

TAKT_TWO_WHEEL_SHARE = 0.30
TAKT_TWO_WHEEL_SPEED_MPS = 4.2
TAKT_TWO_WHEEL_REACH_M = 7000.0
TAKT_TWO_WHEEL_PER_KM_EUR = 0.03
TAKT_TWO_WHEEL_FIXED_S = 240.0
TAKT_TWO_WHEEL_CIRCUITY = 1.5

TAKT_CAR_COST_PER_KM_EUR = 0.25
TAKT_CAR_PARK_EUR = 1.5
TAKT_CAR_PARKING_S = 240.0
TAKT_CAR_CIRCUITY = 1.3
TAKT_CAR_SPEED_KMH = 25.0

# Периодная поправка времени движения авто из Takt (yt = min(mt, 1 + nt·max(0, N/T - 1))).
TAKT_CAR_PERIOD_NT = 0.6
TAKT_CAR_PERIOD_MT = 1.8

TAKT_FARE_BASE_EUR = 0.6
TAKT_FARE_PER_KM_EUR = 0.12
TAKT_FARE_CAP_EUR = 3.0

TAKT_RIDER_BIAS_S = 0.0
TAKT_REST_BASE_SPEED_KMH = 3.6
TAKT_REST_CONT_SPEED_KMH = 5.0
TAKT_REST_ACCESS_S = 420.0
TAKT_REST_WAIT_S = 240.0
TAKT_REST_CIRCUITY = 1.3
